# Generated by Django 3.2.2 on 2021-05-13 09:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('codeDepartement', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nameDepartement', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Departement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codeRegion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nameRegion', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('codeTown', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nameTown', models.CharField(max_length=70)),
                ('centerCoordinateLat', models.FloatField()),
                ('centerCoordinateLong', models.FloatField()),
                ('surface', models.FloatField()),
                ('population', models.IntegerField()),
                ('townPostalcode', models.CharField(max_length=20)),
                ('codeDepartement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='searchTownApp.departement')),
                ('codeRegion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='searchTownApp.region')),
            ],
            options={
                'db_table': 'town',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('codeTownCenter', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='searchTownApp.town')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'center',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='codeRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='searchTownApp.region'),
        ),
    ]
