# Generated by Django 3.2.2 on 2021-05-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodesPostaux',
            fields=[
                ('codePostal', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'code_postaux',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('codeDepartement', models.IntegerField(primary_key=True, serialize=False)),
                ('nameDepartement', models.IntegerField()),
            ],
            options={
                'db_table': 'Departement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('codeRegion', models.IntegerField(primary_key=True, serialize=False)),
                ('nameRegion', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('codeTown', models.IntegerField(primary_key=True, serialize=False)),
                ('nameTown', models.CharField(max_length=70)),
                ('centerCoordinateLat', models.IntegerField()),
                ('centerCoordinateLong', models.IntegerField()),
                ('surface', models.IntegerField()),
                ('population', models.IntegerField()),
                ('codeDepartement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='searchTownApp.departement')),
                ('codeRegion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='searchTownApp.region')),
                ('townPostalcode', models.ManyToManyField(to='searchTownApp.CodesPostaux')),
            ],
            options={
                'db_table': 'town',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='codeRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='searchTownApp.region'),
        ),
    ]
