# Generated by Django 3.2.2 on 2021-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchTownApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='codeDepartement',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
