# Generated by Django 3.2.2 on 2021-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchTownApp', '0002_alter_departement_codedepartement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codespostaux',
            name='codePostal',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nameDepartement',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='region',
            name='codeRegion',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='town',
            name='codeTown',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
